CREATE TABLE IF NOT EXISTS books (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    series TEXT,
    author TEXT,
    min_age BIGINT,
    max_age BIGINT,
    rating TEXT,
    ratings TEXT,
    price NUMERIC,
    cover_type TEXT,
    publication_date TEXT,
    best_seller TEXT,
    link TEXT,
    genres TEXT[] -- ARRAY type for genres
); 